### PR TITLE
Update jmx-metric-gatherer to latest

### PR DESCRIPTION
**Pull request by srv-gh-o11y-gdi**
Update jmx-metric-gatherer to latest

### CODE REVIEW

**Comment by jeffreyc-splunk** [comment]
Requires https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34162

**Comment by atoulme** [comment]
Should be merged after adopting 0.106.0

**Comment by crobert-1** [comment]
I'm going to close and recreate this PR, with the goal of resolving the merge conflict and remove the workflow changes. If my operation doesn't work as expected, I can reopen and use this PR instead.

**Comment by crobert-1** [comment]
Superseded by https://github.com/signalfx/splunk-otel-collector/pull/5240

**Pull request closed without merging**
