### PR TITLE
Add links to component READMEs

### PR DESCRIPTION
**Pull request by asuresh4**
Add links to components in core/contrib.

### CODE REVIEW

**Review by pjanotti — APPROVED** [review]
LGTM

**Comment by jrcamp** [comment]
The links would still work in the table wouldn't they?

**Comment by asuresh4** [comment]
> The links would still work in the table wouldn't they?

Yes, they would. In fact, I did that originally but the diff was hard to read. That's how I ended up with a list. Do we prefer having a table instead of a list?

**Comment by jrcamp** [comment]
Yeah I can see how diff would be hard to read :(. I do think the end result was easier to read and more compact though. I think we should autogenerate this file anyway (or at least this part). If don't want to do that now I'd err on the side of end result being better and can autogenerate later.

**Comment by jrcamp** [comment]
Actually I guess we'd need a way to mark components alpha/beta. Would need to be done upstream in a consistent way. (Maybe factory can return metadata that contains stability status). Not worth blocking this though obviously.

**Comment by asuresh4** [comment]
Ok, in that case I'll restore the table formatting for now. Will update PR shortly.

**Comment by asuresh4** [comment]
@jrcamp ptal

**Review by jrcamp — APPROVED** [review]

**Pull request merged**
