### PR TITLE
Add workflow to lint examples

### PR DESCRIPTION
**Pull request by jeffreyc-splunk**
Run `make lint` for PRs with go-related changes in `examples`.

### CODE REVIEW

**Comment by jeffreyc-splunk** [comment]
Failure is the same issue with the `signalfxgatewayprometheusremotewritereceiver` example that exists in main:
```
Error: fake-metrics-generator.go:42:11: ineffectual assignment to err (ineffassign)
	timeout, err := model.ParseDuration("2s")
	         ^
make: *** [../../Makefile.Common:96: lint] Error 1
```

**Comment by dmitryax** [comment]
Why do we need a separate workflow for the examples? Can we reuse the existing `build-and-test`?

**Comment by jeffreyc-splunk** [comment]
> Why do we need a separate workflow for the examples? Can we reuse the existing `build-and-test`?

My thought was that if a PR only has changes in `examples`, we won't need to run the entire build-and-test workflow, but can still catch issues before it is merged (like #3144 which is currently causing the lint job to fail for the main branch).

**Comment by rmfitzpatrick** [comment]
lint error should be resolved by https://github.com/signalfx/splunk-otel-collector/pull/3167

**Pull request merged**
