### PR TITLE
Add debian 12 support to installer

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
**Description:**
These changes add debian 12 to the installer allowlist and packaging tests.

### CODE REVIEW

**Comment by jeffreyc-splunk** [comment]
https://github.com/signalfx/splunk-otel-collector/blob/main/internal/buildscripts/packaging/installer/install.sh#L96

Should we try upgrading fluentd to [v5](https://td-agent-package-browser.herokuapp.com/5/debian) specifically for bookworm since there are no [v4](https://td-agent-package-browser.herokuapp.com/4/debian) packages?

**Comment by rmfitzpatrick** [comment]
> Should we try upgrading fluentd to [v5](https://td-agent-package-browser.herokuapp.com/5/debian) specifically for bookworm since there are no [v4](https://td-agent-package-browser.herokuapp.com/4/debian) packages?

I was about to ask you :). This would increase the scope of these changes to include vetting the existing fluentd config on v5. Anything else you can thing of?

**Comment by rmfitzpatrick** [comment]
Maybe it's best to disallow fluentd at first and then adopt v5 for https://td-agent-package-browser.herokuapp.com/lts/5/amazon/2023 as well in subsequent changes.

**Comment by jeffreyc-splunk** [comment]
> Maybe it's best to disallow fluentd at first and then adopt v5 for https://td-agent-package-browser.herokuapp.com/lts/5/amazon/2023 as well in subsequent changes.

Probably. You'll need to update https://github.com/signalfx/splunk-otel-collector/blob/main/internal/buildscripts/packaging/installer/install.sh#L797 and https://github.com/signalfx/splunk-otel-collector/blob/main/internal/buildscripts/packaging/tests/installer_test.py#L149.

**Review by jeffreyc-splunk — APPROVED** [review]
Thanks! We'll need to update the changelog, product docs, and the o11y integration wizard whenever this is released.

**Pull request merged**
