### PR TITLE
[connector/forward] Add forward connector support

### PR DESCRIPTION
**Pull request by jinja2**
Adds support for the upstream forward connector

### CODE REVIEW

**Review by crobert-1 — COMMENTED** [review]
Looks good! Were you able to run any basic demo locally to make sure the connector works in our distro?

**Comment by dmitryax** [comment]
Can you please also add a new section to https://github.com/signalfx/splunk-otel-collector/blob/main/docs/components.md ?

**Comment by jinja2** [comment]
> Looks good! Were you able to run any basic demo locally to make sure the connector works in our distro?
@crobert-1 yes, got a test build running in lab


> Can you please also add a new section to https://github.com/signalfx/splunk-otel-collector/blob/main/docs/components.md ?
@dmitryax I have a new table in docs/components.go or are you referring to something else?

**Comment by dmitryax** [comment]
> @dmitryax I have a new table in docs/components.go or are you referring to something else?

I see it now. Sorry, I must have missed it.

Can you please rebase to make sure the PR contains only your changes?

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
