### PR TITLE
Don't override gopsutil env vars in SA receiver

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
Resolves https://github.com/signalfx/splunk-otel-collector/issues/1340 * but is a breaking change to prevent an existing compatibility issue.

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
@dmitryax I also considered using the https://github.com/signalfx/splunk-otel-collector/tree/main/internal/extension/smartagentextension#signalfx-smart-agent-extension in the helm chart instead of these changes but either way the behavior is a little unintuitive.

**Comment by dmitryax** [comment]
I don't think we should solve this issue until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5879 is resolved. Once this is merge collector will be spamming errors in any k8s environment

**Comment by atoulme** [comment]
I note https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5879 was just marked resolved.

**Comment by rmfitzpatrick** [comment]
With https://github.com/signalfx/splunk-otel-collector/pull/3509 I think this PR needs to be updated to have the SA config paths respect the gopsutil common env vars but implementing the `defaults.Setter` interface. Doing that when able.

**Comment by rmfitzpatrick** [comment]
Not going to move forward with this approach for now. Manually specifying in the SA config remains the support path.

**Pull request closed without merging**
