### PR TITLE
Pull recent fixes for resource detection processor from contrib

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Review by dloucasfx — APPROVED** [review]

**Comment by rmfitzpatrick** [comment]
@dmitryax thanks for the fix. Is it ok if I push an edit to an existing integration test to pick up coverage for this?

**Comment by dmitryax** [comment]
> Is it ok if I push an edit to an existing integration test to pick up coverage for this?

Sure, please do 👍

**Comment by rmfitzpatrick** [comment]
pushed https://github.com/dmitryax/splunk-otel-collector/commit/18031f12796392630e3578072a6907a6e869256a but it seems to be taking a minute to reflect here.

**Comment by dmitryax** [comment]
> pushed https://github.com/dmitryax/splunk-otel-collector/commit/18031f12796392630e3578072a6907a6e869256a but it seems to be taking a minute to reflect here.

Thanks! I added a comment right in the commit

**Pull request merged**
