### PR TITLE
Move NGINX discovery to OTel receiver

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
The discovery for NGINX should use the OTel receiver instead of the SmartAgent monitor.

**Link:**
https://splunk.atlassian.net/browse/OTL-2998

**Testing:**
N/A

**Documentation:**

### CODE REVIEW

**Comment by pjanotti** [comment]
Integration test failure:
```
2024-12-12T15:06:20.518Z	INFO	testutils/collector_container.go:267	go.opentelemetry.io/collector/receiver@v0.114.0/scraperhelper/scrapercontroller.go:183
    golden.go:125: 
        	Error Trace:	/home/runner/work/splunk-otel-collector/splunk-otel-collector/tests/testutils/golden.go:127
        	            				/opt/hostedtoolcache/go/1.22.7/x64/src/runtime/asm_amd64.s:1695
        	Error:      	No metrics collected
    golden.go:125: 
        	Error Trace:	/home/runner/work/splunk-otel-collector/splunk-otel-collector/tests/testutils/golden.go:125
        	            				/home/runner/work/splunk-otel-collector/splunk-otel-collector/tests/receivers/apachespark/apachespark_test.go:30
        	Error:      	Condition never satisfied
        	Test:       	TestApacheSparkIntegration
2024/12/12 15:06:34 🐳 Stopping container: c55a7b46c83e
2024-12-12T15:06:34.251Z	INFO	testutils/collector_container.go:267	2024-12-12T15:06:34.250Z	info	otelcol@v0.114.0/collector.go:328	Received signal from OS	{"signal": "terminated"}
2024-12-12T15:06:34.251Z	INFO	testutils/collector_container.go:267	2024-12-12T15:06:34.250Z	info	service@v0.114.0/service.go:303	Starting shutdown...
2024-12-12T15:06:34.251Z	INFO	testutils/collector_container.go:267	2024-12-12T15:06:34.250Z	info	extensions/extensions.go:66	Stopping extensions...
2024-12-12T15:06:34.251Z	INFO	testutils/collector_container.go:267	2024-12-12T15:06:34.250Z	info	service@v0.114.0/service.go:317	Shutdown complete.
2024/12/12 15:06:34 ✅ Container stopped: c55a7b46c83e
2024/12/12 15:06:34 🐳 Stopping container: c55a7b46c83e
2024/12/12 15:06:34 ✅ Container stopped: c55a7b46c83e
2024/12/12 15:06:34 🐳 Terminating container: c55a7b46c83e
2024/12/12 15:06:34 🚫 Container terminated: c55a7b46c83e
--- FAIL: TestApacheSparkIntegration (35.64s)
FAIL
FAIL	github.com/signalfx/splunk-otel-collector/tests/receivers/apachespark	35.663s
```

Re-running...

**Review by swahba — COMMENTED** [review]
I see `smartagent with collectd/nginx monitor type (Linux)` in the README file (https://github.com/signalfx/splunk-otel-collector/tree/main/internal/confmapprovider/discovery#readme). Should that also be updated?

**Comment by pjanotti** [comment]
Eagle eye @swahba! @hughesjj I will remove the obvious ones, but, it still may require some careful reading.

**Comment by pjanotti** [comment]
@hughesjj it will be a bit messy: there are files to be deleted, links to be checked, etc. I will fix the one related to NGINX and will do a separate PR to fix the others.

**Pull request merged**
