### PR TITLE
Release v0.42.0

### PR DESCRIPTION
**Pull request by jcheng-splunk**

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
Any chance https://github.com/signalfx/splunk-otel-collector/pull/1150 can make this release?

**Comment by jcheng-splunk** [comment]
>

**Comment by jcheng-splunk** [comment]
> Any chance #1150 can make this release?

Yep, just add it to the changelog in your PR and I'll rebase when it is merged.

**Review by rmfitzpatrick — APPROVED** [review]
integration looks good

**Pull request merged**
