### PR TITLE
Run make binaries-windows_amd64 clean on Windows

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
Change Makefile so `make binaries-windows_amd64` runs clean on Windows. This is the same fix done on contrib to avoid errors while running `make` on Windows.
 
**Link to Splunk idea:**
N/A

**Testing:**
- Ran it locally (only validated the target `binaries-windows_amd64`.

**Documentation:**
N/A

### CODE REVIEW

**Comment by pjanotti** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pjanotti** [comment]
recheck

**Comment by rmfitzpatrick** [comment]
Interesting this isn't triggering the workflows that have the file in their paths PR sequence.

**Comment by jinja2** [comment]
Might be due to paths being case-sensitive. The [workflows have a typo](https://github.com/signalfx/splunk-otel-collector/blob/main/.github/workflows/win-package-test.yml#L17), the filename is `Makefile.Common`.

**Comment by pjanotti** [comment]
Closing and reopening to see if it triggers the workflows after Jina's fix.

**Review by jinja2 — APPROVED** [review]

**Comment by pjanotti** [comment]
@jinja2 thanks for the workflow fixes!

**Pull request merged**
