### PR TITLE
feat: add all scripts to pipeline

### PR DESCRIPTION
**Pull request by weliasz**
**Description:** Add all scripts to pipeline

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
@weliasz why is this necessary when a single instance could be adequate for an example? We don't include all the variations of receivers in this or any other config.

**Comment by weliasz** [comment]
Not sure if this is necessary. I just wanted to make sure we deliver full config for target deployment. If this would be done some other way and we don't need to worry about it in this file maybe this PR could be closed.

**Comment by atoulme** [comment]
The intent is a bit fuzzy at this point, that's for sure. I guess if we add all those receivers we drive home the point it's ready for testing, and folks can pick it up without building their own yaml.

**Comment by atoulme** [comment]
After discussing with @rmfitzpatrick I think we need to discuss this yaml file and probably just move it out of the way. My suggestion is that we accept this change and merge it, and then cut off this to an example so we can offer it for folks to try it out without having them figure out the yaml.

**Review by atoulme — APPROVED** [review]

**Pull request merged**
