### PR TITLE
Update breaking changes for installer modules

### PR DESCRIPTION
**Pull request by jeffreyc-splunk**

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Comment by aunshc** [comment]
Thanks Jeff, LGTM!

**Comment by aunshc** [comment]
Once https://github.com/signalfx/splunk-otel-collector/pull/3851/files is merged, I suggest added a note about the deprecated installer script options in the changelog as well.

**Comment by aunshc** [comment]
Once https://github.com/signalfx/splunk-otel-collector/pull/3851/files is merged, I suggest adding a note about the deprecated installer script options in the changelog as well.

**Comment by jeffreyc-splunk** [comment]
> Once https://github.com/signalfx/splunk-otel-collector/pull/3851/files is merged, I suggest adding a note about the deprecated installer script options in the changelog as well.

See https://github.com/signalfx/splunk-otel-collector/pull/3851/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Pull request merged**
