### PR TITLE
added mongodb receiver from collector contrib

### PR DESCRIPTION
**Pull request by shalper2**
**Description:**  Adds support for the [mongodb](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbreceiver) receiver from the [opentelemetry contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib). 

**Testing:** components_test.go has been updated to reflect these changes

**Documentation:** components.md has been updated to show the new component

### CODE REVIEW

**Comment by shalper2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by atoulme** [comment]
recheck

**Comment by atoulme** [comment]
@shalper2 please re-author your commits to make sure they match your github id and email.

**Comment by shalper2** [comment]
Pretty sure i fixed it

**Review by atoulme — APPROVED** [review]

**Pull request merged**
