### PR TITLE
added to components.go

### PR DESCRIPTION
**Pull request by shalper2**
**Description:** 

Added upstream [Splunk Enterprise](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkenterprisereceiver) receiver to the Splunk-otelcol distro.

### CODE REVIEW

**Comment by atoulme** [comment]
Hang on, you're hitting issues with the otel upgrade. We can help, but need to upgrade otel dependencies in a separate PR.

**Comment by shalper2** [comment]
Yep -- no problem! ill keep an eye and rebase when it goes out.

**Comment by crobert-1** [comment]
This can be updated now 👍

**Review by jvoravong — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by shalper2** [comment]
@atoulme done!

**Pull request merged**
